# -*- coding: utf-8 -*-
"""Создание таблиц в Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJpFqOWtPm3ee4SMiU6U1qu-gBeg9R__
"""

!pip install prettytable

from prettytable import PrettyTable

receipt = PrettyTable()
receipt.field_names = ['№','Продукт','Цена','Количество','Стоимость']

print(receipt)